INSERT INTO regiones (id, nombre) VALUES (1, "Sudamérica");
INSERT INTO regiones (id, nombre) VALUES (2, "Centroamérica");
INSERT INTO regiones (id, nombre) VALUES (3, "Norteamérica");
INSERT INTO regiones (id, nombre) VALUES (4, "Europa");
INSERT INTO regiones (id, nombre) VALUES (5, "Asia");
INSERT INTO regiones (id, nombre) VALUES (6, "Africa");
INSERT INTO regiones (id, nombre) VALUES (7, "Oceanía");
INSERT INTO regiones (id, nombre) VALUES (8, "Antártida");

INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (1, "Andrés", "Guzmán", "andres@mail.com", "2022-06-11");
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (2, "John", "Doe", "john@mail.com", "2022-06-10");
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (4, "Linus", "Torvalds", "linus@mail.com", "2022-06-09");
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (4, "Rasmus", "Leardof", "rasmus@mail.com", "2022-06-08");
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (4, "Erich", "Gamma", "erich@mail.com", "2022-05-11");
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (3, "Richard", "Helm", "richard@mail.com", "2022-05-10");
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (3, "Ralph", "Johnson", "ralph@mail.com", "2022-05-09");
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (1, "Matías", "Blanco", "matias@mail.com", "2022-05-08");
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (5, "Goku", "Son", "goku@mail.com", "2022-04-11");
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (1, "Pepe", "Argento", "pepe@mail.com", "2022-04-10");
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (7, "Juan", "Hernández", "juan@mail.com", "2022-04-09");
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (6, "María", "Soledad", "maria@mail.com", "2022-04-08");